\ Test: Loops
\ Expected: DO/LOOP, BEGIN/UNTIL, and BEGIN/WHILE/REPEAT work

VARIABLE SUM
: DOSUM 0 SUM ! 0 10 DO I SUM @ + SUM ! LOOP ;
DOSUM
SUM @ 45 = IF 42 EMIT ELSE 70 EMIT THEN CR

VARIABLE COUNT
: COUNTDOWN 5 COUNT ! BEGIN COUNT @ 1 - COUNT ! COUNT @ 0= UNTIL ;
COUNTDOWN
COUNT @ 0 = IF 42 EMIT ELSE 70 EMIT THEN CR

\ Test +LOOP
VARIABLE SUM2
: PLUSLOOP_SUM 0 SUM2 ! 0 10 DO I SUM2 @ + SUM2 ! 2 +LOOP ;
PLUSLOOP_SUM
SUM2 @ 20 = IF 42 EMIT ELSE 70 EMIT THEN CR

\ Test BEGIN WHILE REPEAT
VARIABLE N
: WHILE_TEST 0 N ! 0 BEGIN DUP 5 < WHILE N @ 1 + N ! 1 + REPEAT DROP ;
WHILE_TEST
N @ 5 = IF 42 EMIT ELSE 70 EMIT THEN CR

bye
