\ Test: Variables and constants
\ Expected: Variables can be stored and fetched

VARIABLE X
42 X !
X @ 42 = IF 42 EMIT ELSE 70 EMIT THEN CR

100 CONSTANT LIMIT
LIMIT 100 = IF 42 EMIT ELSE 70 EMIT THEN CR

VARIABLE COUNTER
: INCREMENT COUNTER @ 1 + COUNTER ! ;
0 COUNTER !
INCREMENT INCREMENT INCREMENT
COUNTER @ 3 = IF 42 EMIT ELSE 70 EMIT THEN CR

bye
